const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
const GET_DATA_FAILURE = "GET_DATA_FAILURE"
const GET_DATA_REQUEST = "GET_DATA_REQUEST"

const GET_PAGE_SUCCESS = "GET_PAGE_SUCCESS"
const GET_PAGE_FAILURE = "GET_PAGE_FAILURE"
const GET_PAGE_REQUEST = "GET_PAGE_REQUEST"

const GET_MALE_FILTER_SUCCESS = "GET_MALE_FILTER_SUCCESS"
const GET_MALE_FILTER_FAILURE = "GET_MALE_FILTER_FAILURE"
const GET_MALE_FILTER_REQUEST = "GET_MALE_FILTER_REQUEST"

const GET_FEMALE_FILTER_SUCCESS = "GET_FEMALE_FILTER_SUCCESS"
const GET_FEMALE_FILTER_FAILURE = "GET_FEMALE_FILTER_FAILURE"
const GET_FEMALE_FILTER_REQUEST = "GET_FEMALE_FILTER_REQUEST"

const GET_AGE_SORT_SUCCESS = "GET_AGE_SORT_SUCCESS"
const GET_AGE_SORT_FAILURE = "GET_AGE_SORT_FAILURE"
const GET_AGE_SORT_REQUEST = "GET_AGE_SORT_REQUEST"

const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS"
const GET_SEARCH_FAILURE = "GET_SEARCH_FAILURE"
const GET_SEARCH_REQUEST = "GET_SEARCH_REQUEST"